### ISSUE TITLE
How to select the multiple date.

### ISSUE THREAD

**Issue by sks1990** [marekpetras/yii2-calendarview-widget#1]
Hello All,

I am using the "yii2-calendarview-widget " ,How to select the multiple date and disable the parvius date for today.

thanks

**Comment by marekpetras** [comment]
Hey @sks1990 ,

what exactly do you mean select multiple dates? Highlight them? The css class "today" is being added in @widget/views/day.php 

You can create your own view for a day and highlight whichever you want.

Just specify path to the new day view in the widget config : 

``` php
echo CalendarView::widget(
    [
        'views'     => [
            'day' => '@vendor/marekpetras/yii2-calendarview-widget/views/day',
        ],
]
);
```

If you mean something else, please attach some code and I can have a look.

Cheers,
Marek
