### ISSUE TITLE
Doesn't installing via composer

### ISSUE THREAD

**Issue by ossoom** [marekpetras/yii2-calendarview-widget#3]
Hi. I can not install yii2-calendarview-widger via composer. I'm trying to install it by `composer require --prefer-dist marekpetras/yii2-calendarview "1.0.0"` and it gives me message: 

```

- The requested package marekpetras/yii2-calendarview could not be found in any version, there may be a typo in package name. 

Potential causes: 
- A typo in the package name
- The package is not available is a stable-enough version according to your minimum-stability setting
```

How to solve this problem? I need your help.

**Comment by marekpetras** [comment]
Hey @samatic ,

you got a typo there, the package name is marekpetras/yii2-calendarview-widget 

Cheers,
Marek

**Comment by ossoom** [comment]
Thank you. But you should fix it here http://www.yiiframework.com/extension/yii2-calendarview/

**Comment by marekpetras** [comment]
Oh cool, thanks for the tip, changed it there.
