### ISSUE TITLE
Can i use date field with int type not datetime?

### ISSUE THREAD

**Issue by ossoom** [marekpetras/yii2-calendarview-widget#4]
Hi. It's me again. I have another question.

I usually save dates in database as timestamps. And i use INT data type not DATETIME like it's written in your usage instruction. 

How can i use your extenstion with timestamps?

I would be very grateful if you could help me.

**Comment by marekpetras** [comment]
Hey,

update your release to v1.0.1, I added the option 'unixTimestamp' to indicate whether you are dealing with a text/date/datetime or a unix timestamp field to correctly determine the date of the model from the provider.

After you update, all you should need to do is too do a 'unixTimestamp' => true, in your widget config and thats it.

Cheers,
Marek

**Comment by ossoom** [comment]
Thanks a lot. You are really helped me.

**Comment by marekpetras** [comment]
Not a problem @samatic , project you are working on is public? Would you mind sharing it?

**Comment by ossoom** [comment]
I'm not sure about what do you men public. But i'm working on some little local goverment website. Your extension saved my time very much. Thank you again, you are very kind person ;)

**Comment by marekpetras** [comment]
Public, as in can I see the widget online somewhere? If so, can you send the url ?

You are very welcome.

Cheers,
Marek

**Comment by ossoom** [comment]
Sure. I'll send you url when work will be done.
