### ISSUE TITLE
Activity Model Missing

### ISSUE THREAD

**Issue by gogl92** [marekpetras/yii2-calendarview-widget#5]
Do you have an example of a Activity Model?, this must be added to the documentation to use it as it is, also the Calendar view:

`            return ['calendar/view','id'=>$model->id];
`

**Comment by marekpetras** [comment]
Hey mate,

as a matter of fact, that specific callback will be passed one of the models retrieved from the data provider, in this case the Calendar from the example.

The purpose of that is so you can get a different link on the value from each model, e.g. linking to the models detail page or whatever.

Cheers
