### ISSUE TITLE
No way to specify an end date?

### ISSUE THREAD

**Issue by noc2spam** [marekpetras/yii2-calendarview-widget#6]
This widget is super lovely, but I am stuck with events that spans for multiple days. Let's say, a room booking model that has a start_day, and an end_day. There doesn't seem to be any way to implement this, or am I missing something? :)

**Comment by marekpetras** [comment]
hi @noc2spam , sorry for the extremely late answer :) thanks for the usage ...
events spanning multiple days was never my use case, happy for you to submit a PR adding support for that :) 

cheers
