### ISSUE TITLE
How to Change Views ?

### ISSUE THREAD

**Issue by Andyal15** [marekpetras/yii2-calendarview-widget#7]
Hy,
I've installed your Calendar Tool and I#m not able to change the view to month or day.
I've uncommended:
 'views'     => [
			//'calendar' => '@vendor/marekpetras/yii2-calendarview-widget/views/calendar',
			'month' => '@vendor/marekpetras/yii2-calendarview-widget/views/month',
            //'day' => '@vendor/marekpetras/yii2-calendarview-widget/views/day',
        ],
But then i get error -> 
PHP Notice – yii\base\ErrorException
Undefined index: day
THX
Andy

**Comment by marekpetras** [comment]
hey @Andyal15 

you can replace them with your own views, but they need to be defined

just copy those files from your vendor folder somewhere, modify them to your liking and specify the path in the views array

cheers
